### ISSUE TITLE
version properties not resolved in imported boms on mvn goal package

### ISSUE THREAD

**Issue by maybeec** [mojohaus/flatten-maven-plugin#26]
I just run a new build of the [oasp/oasp4j](https://github.com/oasp/oasp4j) just executing the `mvn package` goal rather than the `install` goal. This leads to a build error in the [beanmapping module](https://github.com/oasp/oasp4j/blob/develop/modules/beanmapping/pom.xml) as the version for

``` xml
<dependency>
      <groupId>net.sf.m-m-m</groupId>
      <artifactId>mmm-util-entity</artifactId>
</dependency>
```

could not be resolved. The version is managed in the [oasp4j-bom](https://github.com/oasp/oasp4j/blob/develop/bom/pom.xml). It seems that the version property `${mmm.util.version}` could not be resolved running `mvn package`. However, running `mvn install` everything is working.

**Comment by cboehme** [comment]
I tried to replicate the problem with a minimal project. The code can be found at [cboehme/bom-flatten-error](https://github.com/cboehme/bom-flatten-error). When running `mvn package` in the top-level directory of this project the build will fail with the following error message:

> [ERROR] [FATAL] Non-readable POM /home/christoph/.m2/repository/net/b3e/bom-module/1.0.0-SNAPSHOT/bom-module-1.0.0-SNAPSHOT.pom: /home/christoph/.m2/repository/net/b3e/bom-module/1.0.0-SNAPSHOT/bom-module-1.0.0-SNAPSHOT.pom (No such file or directory) @ /home/christoph/.m2/repository/net/b3e/bom-module/1.0.0-SNAPSHOT/bom-module-1.0.0-SNAPSHOT.pom

As described by @maybeec running `mvn install` works, though. I also notices that after having run `mvn install` once, `mvn package` will also work.

Wit the help of the example project, I tried to find out what caused the problem. Here is what I found out:

The problem occurs when creating the effective pom ([see here](https://github.com/mojohaus/flatten-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java#L689)). In order to build the effective pom, the reference to the BOM needs to be resolved. This fails because the flatten-maven-plugin defines its own `ModelResolver` which relies on the referenced models being in the local repository. It is assumed that Maven will resolve all dependencies before calling the plugin's flatten goal. While this assumption holds true for external dependencies, it does not work for inter-modules dependencies. These are not added to the local repository unless `mvn install` is invoked. 

To solve the problem the [`FlattenModelResolver`](https://github.com/mojohaus/flatten-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java) needs to be extended to keep a list of modules in the project being built. However, such a list does not seem to available. The `MavenSession` contains a property `allProjects` which according to comments in the source code should contain all projects in a multi-module project, but in reality it contains only the projects being in the project list. 

I have currently no idea how this problem could be solved.

**Comment by cboehme** [comment]
I proposed a fix for the `allProjects` property in Maven Core. See [MNG-6173](https://issues.apache.org/jira/browse/MNG-6173) and this [pull request](https://github.com/apache/maven/pull/105).

**Comment by ChristianSchulte** [comment]
Although unrelated to the issue, please note that the `ModelResolver` interface has been enhanced starting with Maven 3.5.0-alpha-1. Additionally, please keep in mind that the `public ModelSource resolveModel( Parent parent )` and `public ModelSource resolveModel( Dependency dependency )` methods need to be prepared to deal with version ranges. You may need to compile the plugin against Maven 3.5.0-alpha-1 to have the `FlattenModelResolver` support Maven >= 3.5.0-alpha-1 correctly.

**Comment by cboehme** [comment]
When compiling against Maven 3.5.0-alpha-1, everything works as expected. I updated pull request #34 to compile the plugin against this Maven version.
Handling parent version ranges in the plugin seems to be a bit tricky. I tried to implement it, but could not get it to work. I created issue #36 for this.

**Comment by khmarbaise** [comment]
@cboehme maybe you could show what you have so far...maybe we find together a solution?

**Comment by cboehme** [comment]
@khmarbaise so far I have the following:

In pull request #34 I fixed the issue that version properties are not resolved in imported boms for dependencies specified with a single version. This works as excepted.

Pull Request #38 contains an integration test for using parent versions with version ranges (issue #36) and my first unsuccessful attempt to add support for this (see commit c886fcd7ad8e6ba28397cbdb855e2c5958d3ac9c).

I rebased both pull requests so that the apply cleanly on current master.
