### ISSUE TITLE
nexus staging plugin ends up in flattened pom.

### ISSUE THREAD

**Issue by benson-basis** [mojohaus/flatten-maven-plugin#28]
My flattened pom ends up with the following.  Is there a way to avoid this? It's not interesting to the flat consumer

```
<build>
    <plugins>
      <plugin>
        <groupId>org.sonatype.plugins</groupId>
        <artifactId>nexus-staging-maven-plugin</artifactId>
        <version>1.6.5</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
```

**Comment by cowwoc** [comment]
There is no harm in this. In fact, I would say that one shouldn't remove configuration that was used to build the project (because it helps others reproduce the build later on if they need to). Just my 2 cents.

**Comment by cboehme** [comment]
I tested this and can confirm that the plugin declaration stays in the pom. Being surprised by this behaviour, I tried to remove the `<extensions>true</extensions>` setting. Without this setting the plugin is removed from the pom as expected. 

Reading up on the [meaning of the extensions setting](http://maven.apache.org/pom.html#Extensions), it seems that it is used for plugins that amend the build's classpath. Which is probably the reason why it stays in the flattened pom. A [comment](https://github.com/mojohaus/flatten-maven-plugin/blob/da57c9acb21eab8a193968bcad6918525d279b4f/src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java#L473) in the code makes clear that this behaviour of the flatten plugin is intentional. I think, it would be good to mention this in the documentation.

I also tried moving the plugin declaration to the `<pluginManagement>` section. This removed the plugin from the flattened pom. Perhaps this is an option for you.
