### ISSUE TITLE
Build Issues on travis

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/flatten-maven-plugin#75]

**Comment by lasselindqvist** [comment]
The solution could be passing -Dhttps.protocols=TLSv1.2 to the Travis CI build. I am not sure how to do that so that it is available when the Maven installation is being downloaded though. Maybe https://docs.travis-ci.com/user/environment-variables/ ?

**Comment by deathrowe** [comment]
Has there been any update on this? I would love to use this in my day to day

**Comment by patrickjamesbarry** [comment]
Is there anything in the way of this change merging, and the ticket closing?

**Comment by taxone** [comment]
I also need this feature, it will be much appreciated.

**Comment by lasselindqvist** [comment]
As it seems that this is not making any progress due to busyness of the main contributors I suggest building your own JAR meanwhile from https://github.com/lasselindqvist/flatten-maven-plugin/tree/ci-friendly

I have no intention of maintaining a fork, but @khmarbaise if you need someone to take over the main repository, I am happy to help you with that.

**Comment by khmarbaise** [comment]
Currently I'm sitting on Devoxx Belgium on a hackspace ...so I have some time...

**Comment by taxone** [comment]
> As it seems that this is not making any progress due to busyness of the main contributors I suggest building your own JAR meanwhile from https://github.com/lasselindqvist/flatten-maven-plugin/tree/ci-friendly
> 
> I have no intention of maintaining a fork, but @khmarbaise if you need someone to take over the main repository, I am happy to help you with that.

It works very well, thanks a lot!
