### ISSUE TITLE
keeping pluginManagement

### ISSUE THREAD

**Issue by gdelafosse** [mojohaus/flatten-maven-plugin#9]
Hello
is there a way to flatten and keep pluginManagment section?

**Comment by hohwille** [comment]
Actually I once had implemented a way to enable that all POM elemens can be configured to keep. That change has however been reverted after some discussion. I assume you want to use flattening for a POM with packaging pom and there is some reason in your use-case to keep pluginManagemnet. 
I am fine with this change. We only will not re-introduce that elements such as build should be keept. In such case one should use a different plugin (e.g. if he only wants to resolve some variables but keep everything else as is).

**Comment by hohwille** [comment]
A bigger problem is that there are two important bugs #3 and #5 outstanding that I would love to fix for the upcoming release. But I would need some support on that and no-one of the maven gurus seems to be available for giving me the right hints. I you seriously rely on this issue here, let me know so I might be up for an intermediate release...

**Comment by gdelafosse** [comment]
I can wait. Thanks

**Comment by hohwille** [comment]
PR has been merged.

**Comment by gdelafosse** [comment]
thanks

**Comment by hohwille** [comment]
Release is prepared. You are welcome to test and vote:
https://groups.google.com/forum/#!topic/mojohaus-dev/kHVNoyGvK5o
